version: '2'
services:
    jtrs-app:
        image: jtrs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jtrs-mariadb:3306/jtrs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jtrs-elasticsearch:9300
        ports:
            - 8080:8080
    jtrs-mariadb:
        extends:
            file: mariadb.yml
            service: jtrs-mariadb
    jtrs-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jtrs-elasticsearch
